const worksList = [
  {
    id: 1,
    month: "01",
    title: "瑾琪AIC智慧校园微信端",
    keyword: "(jQuery+vue2/3)",
    image: `/images/1.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    link: "./src/doc/works/1.md",
  },
  {
    id: 2,
    month: "02",
    title: "SONA",
    image: `/images/2.jpg`,
    keyword: "(jQuery+vue2/3)",
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    link: "./src/doc/works/1.md",
  },
  {
    id: 3,
    month: "03",
    title: "SONA",
    image: `/images/3.jpg`,
    keyword: "(jQuery+vue2/3)",
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    link: "./src/doc/works/1.md",
  },
  {
    id: 4,
    month: "04",
    title: "SONA",
    image: `/images/4.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 5,
    month: "05",
    title: "SONA",
    image: `/images/5.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 6,
    month: "06",
    title: "SONA",
    image: `/images/6.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 7,
    month: "07",
    title: "SONA",
    image: `/images/7.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 8,
    month: "08",
    title: "SONA",
    image: `/images/8.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
 },
  {
    id: 9,
    month: "09",
    title: "SONA",
    image: `/images/9.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 10,
    month: "10",
    title: "SONA",
    image: `/images/10.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 11,
    month: "11",
    title: "SONA",
    image: `/images/11.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
  {
    id: 12,
    month: "12",
    title: "SONA",
    image: `/images/12.jpg`,
    description: "AIC智慧校园微信端是一个提高校园管理效率和便利性的综合性平台。支持单点登录，该平台支持多种角色，在日常工作中 提供了一系列功能和服务。",
    keyword: "(jQuery+vue2/3)",
    link: "./src/doc/works/1.md",
  },
];

export default worksList;
